project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - "*/index.qmd"
  preview: 
    port: 4200
  resources:
    - cgvc2025_backup/**

website:
  title: "Presentations"
  # navbar:
  #   left:
  #     - text: "Home"
  #       href: index.qmd

format:
  html:
    theme: cosmo
    toc: false

